/* eslint-disable @typescript-eslint/naming-convention */
import { ModelCatalog, ModelState } from '@janhq/core'

export const dummyModel: ModelCatalog = {
  id: 'aladar/TinyLLama-v0-GGUF',
  name: 'TinyLLama-v0-GGUF',
  shortDescription: 'TinyLlama-1.1B-Chat-v0.3-GGUF',
  longDescription: 'https://huggingface.co/aladar/TinyLLama-v0-GGUF/tree/main',
  avatarUrl: '',
  releaseDate: Date.now(),
  author: 'aladar',
  version: '1.0.0',
  modelUrl: 'aladar/TinyLLama-v0-GGUF',
  tags: ['freeform', 'tags'],
  availableVersions: [
    {
      object: 'model',
      version: '1.0.0',
      source_url:
        'https://huggingface.co/aladar/TinyLLama-v0-GGUF/resolve/main/TinyLLama-v0.Q8_0.gguf',
      id: 'TinyLLama-v0.Q8_0.gguf',
      name: 'TinyLLama-v0.Q8_0.gguf',
      owned_by: 'you',
      created: 0,
      description: '',
      state: ModelState.ToDownload,
      settings: {
        ctx_len: 2048,
        ngl: 100,
        embedding: true,
        n_parallel: 4,
      },
      parameters: {
        temperature: 0.7,
        token_limit: 2048,
        top_k: 0,
        top_p: 1,
        stream: true,
      },
      metadata: {
        engine: '',
        quantization: '',
        size: 5816320,
        binaries: [],
        maxRamRequired: 256000000,
        author: 'aladar',
        avatarUrl: '',
      },
    },
    {
      object: 'model',
      version: '1.0.0',
      source_url:
        'https://huggingface.co/aladar/TinyLLama-v0-GGUF/resolve/main/TinyLLama-v0.f16.gguf',
      id: 'TinyLLama-v0.f16.gguf',
      name: 'TinyLLama-v0.f16.gguf',
      owned_by: 'you',
      created: 0,
      description: '',
      state: ModelState.ToDownload,
      settings: {
        ctx_len: 2048,
        ngl: 100,
        embedding: true,
        n_parallel: 4,
      },
      parameters: {
        temperature: 0.7,
        token_limit: 2048,
        top_k: 0,
        top_p: 1,
        stream: true,
      },
      metadata: {
        engine: '',
        quantization: '',
        size: 5816320,
        binaries: [],
        maxRamRequired: 256000000,
        author: 'aladar',
        avatarUrl: '',
      },
    },
    {
      object: 'model',
      version: '1.0.0',
      source_url:
        'https://huggingface.co/aladar/TinyLLama-v0-GGUF/resolve/main/TinyLLama-v0.f32.gguf',
      id: 'TinyLLama-v0.f32.gguf',
      name: 'TinyLLama-v0.f32.gguf',
      owned_by: 'you',
      created: 0,
      description: '',
      state: ModelState.ToDownload,
      settings: {
        ctx_len: 2048,
        ngl: 100,
        embedding: true,
        n_parallel: 4,
      },
      parameters: {
        temperature: 0.7,
        token_limit: 2048,
        top_k: 0,
        top_p: 1,
        stream: true,
      },
      metadata: {
        engine: '',
        quantization: '',
        size: 5816320,
        binaries: [],
        maxRamRequired: 256000000,
        author: 'aladar',
        avatarUrl: '',
      },
    },
  ],
}
