export const route = {
  // home as new chat or thread
  home: '/',
  appLogs: '/logs',
  assistant: '/assistant',
  settings: {
    index: '/settings',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    appearance: '/settings/appearance',
    privacy: '/settings/privacy',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    local_api_server: '/settings/local-api-server',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    hardware: '/settings/hardware',
    rag: '/settings/rag',
  },
  hub: '/hub',
  ragDocuments: '/rag-documents',
  localApiServerlogs: '/local-api-server/logs',
  systemMonitor: '/system-monitor',
  threadsDetail: '/threads/$threadId',
}
