const COMMANDS: &[&str] = &[
    // Cleanup command
    "cleanup_llama_processes",
    // LlamaCpp server commands
    "load_llama_model",
    "unload_llama_model",
    // Router-mode commands (Phase 1)
    "start_router",
    "stop_router",
    "try_graceful_stop_router",
    "force_kill_router_tree",
    "get_router_info",
    "reload_router_models",
    "router_slots_idle",
    "router_health",
    "adopt_router",
    "get_devices",
    "generate_api_key",
    "ensure_session_ready",
    "find_session_by_model",
    "get_loaded_models",
    // GGUF commands
    "read_gguf_metadata",
    "estimate_kv_cache_size",
    "get_model_size",
    "is_model_supported",
    // backend management
    "map_old_backend_to_new",
    "get_local_installed_backends",
    "list_supported_backends",
    "determine_supported_backends",
    "get_supported_features",
    "is_cuda_installed",
    "find_latest_version_for_backend",
    "prioritize_backends",
    "parse_backend_version",
    "check_backend_for_updates",
    "remove_old_backend_versions",
    "validate_backend_string",
    "should_migrate_backend",
    "handle_setting_update",
    // Backend path & download commands
    "get_backend_dir",
    "get_backend_exe_path",
    "check_backend_installed",
    "verify_backend_installation",
    "fetch_remote_supported_backends",
    "build_backend_download_items",
    "fetch_backend_checksums",
    "verify_file_sha512",
];

fn main() {
    // `tauri_plugin::Builder` creates command permission files but never removes
    // obsolete ones. Clear that derived input first so removed commands cannot
    // remain in the schema or generated reference.
    let commands_dir = std::path::Path::new("permissions/autogenerated/commands");
    if commands_dir.exists() {
        std::fs::remove_dir_all(commands_dir)
            .expect("failed to remove stale generated command permissions");
    }
    tauri_plugin::Builder::new(COMMANDS).build();
}
