import { SessionInfo, UnloadResult, MlxConfig } from './types';
export { SessionInfo, UnloadResult, MlxConfig } from './types';
export declare function normalizeMlxConfig(config: any): MlxConfig;
export declare function loadMlxModel(binaryPath: string, modelId: string, modelPath: string, port: number, cfg: MlxConfig, envs: Record<string, string>, isEmbedding?: boolean, timeout?: number): Promise<SessionInfo>;
export declare function unloadMlxModel(pid: number): Promise<UnloadResult>;
export declare function isMlxProcessRunning(pid: number): Promise<boolean>;
export declare function getMlxRandomPort(): Promise<number>;
export declare function findMlxSessionByModel(modelId: string): Promise<SessionInfo | null>;
export declare function getMlxLoadedModels(): Promise<string[]>;
export declare function getMlxAllSessions(): Promise<SessionInfo[]>;
