/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MiniAppsImport } from './routes/mini-apps'
import { Route as HelpImport } from './routes/help'
import { Route as IndexImport } from './routes/index'
import { Route as ThreadsThreadIdImport } from './routes/threads/$threadId'
import { Route as SettingsShortcutsImport } from './routes/settings/shortcuts'
import { Route as SettingsPrivacyImport } from './routes/settings/privacy'
import { Route as SettingsMcpServersImport } from './routes/settings/mcp-servers'
import { Route as SettingsLocalApiServerImport } from './routes/settings/local-api-server'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as SettingsExtensionsImport } from './routes/settings/extensions'
import { Route as SettingsAppearanceImport } from './routes/settings/appearance'
import { Route as LocalApiServerLogsImport } from './routes/local-api-server/logs'
import { Route as SettingsProvidersProviderNameImport } from './routes/settings/providers/$providerName'

// Create/Update Routes

const MiniAppsRoute = MiniAppsImport.update({
  id: '/mini-apps',
  path: '/mini-apps',
  getParentRoute: () => rootRoute,
} as any)

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsThreadIdRoute = ThreadsThreadIdImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRoute,
} as any)

const SettingsShortcutsRoute = SettingsShortcutsImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRoute,
} as any)

const SettingsPrivacyRoute = SettingsPrivacyImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRoute,
} as any)

const SettingsMcpServersRoute = SettingsMcpServersImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRoute,
} as any)

const SettingsLocalApiServerRoute = SettingsLocalApiServerImport.update({
  id: '/settings/local-api-server',
  path: '/settings/local-api-server',
  getParentRoute: () => rootRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRoute,
} as any)

const SettingsExtensionsRoute = SettingsExtensionsImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRoute,
} as any)

const SettingsAppearanceRoute = SettingsAppearanceImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRoute,
} as any)

const LocalApiServerLogsRoute = LocalApiServerLogsImport.update({
  id: '/local-api-server/logs',
  path: '/local-api-server/logs',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/mini-apps': {
      id: '/mini-apps'
      path: '/mini-apps'
      fullPath: '/mini-apps'
      preLoaderRoute: typeof MiniAppsImport
      parentRoute: typeof rootRoute
    }
    '/local-api-server/logs': {
      id: '/local-api-server/logs'
      path: '/local-api-server/logs'
      fullPath: '/local-api-server/logs'
      preLoaderRoute: typeof LocalApiServerLogsImport
      parentRoute: typeof rootRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceImport
      parentRoute: typeof rootRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsImport
      parentRoute: typeof rootRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof rootRoute
    }
    '/settings/local-api-server': {
      id: '/settings/local-api-server'
      path: '/settings/local-api-server'
      fullPath: '/settings/local-api-server'
      preLoaderRoute: typeof SettingsLocalApiServerImport
      parentRoute: typeof rootRoute
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersImport
      parentRoute: typeof rootRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyImport
      parentRoute: typeof rootRoute
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/mini-apps': typeof MiniAppsRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/mini-apps': typeof MiniAppsRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/mini-apps': typeof MiniAppsRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/mini-apps'
    | '/local-api-server/logs'
    | '/settings/appearance'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/mini-apps'
    | '/local-api-server/logs'
    | '/settings/appearance'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/mini-apps'
    | '/local-api-server/logs'
    | '/settings/appearance'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  MiniAppsRoute: typeof MiniAppsRoute
  LocalApiServerLogsRoute: typeof LocalApiServerLogsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsLocalApiServerRoute: typeof SettingsLocalApiServerRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  MiniAppsRoute: MiniAppsRoute,
  LocalApiServerLogsRoute: LocalApiServerLogsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsLocalApiServerRoute: SettingsLocalApiServerRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/help",
        "/mini-apps",
        "/local-api-server/logs",
        "/settings/appearance",
        "/settings/extensions",
        "/settings/general",
        "/settings/local-api-server",
        "/settings/mcp-servers",
        "/settings/privacy",
        "/settings/shortcuts",
        "/threads/$threadId",
        "/settings/providers/$providerName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/mini-apps": {
      "filePath": "mini-apps.tsx"
    },
    "/local-api-server/logs": {
      "filePath": "local-api-server/logs.tsx"
    },
    "/settings/appearance": {
      "filePath": "settings/appearance.tsx"
    },
    "/settings/extensions": {
      "filePath": "settings/extensions.tsx"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx"
    },
    "/settings/local-api-server": {
      "filePath": "settings/local-api-server.tsx"
    },
    "/settings/mcp-servers": {
      "filePath": "settings/mcp-servers.tsx"
    },
    "/settings/privacy": {
      "filePath": "settings/privacy.tsx"
    },
    "/settings/shortcuts": {
      "filePath": "settings/shortcuts.tsx"
    },
    "/threads/$threadId": {
      "filePath": "threads/$threadId.tsx"
    },
    "/settings/providers/$providerName": {
      "filePath": "settings/providers/$providerName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
