/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp-servers'
import { Route as SettingsLocalApiServerRouteImport } from './routes/settings/local-api-server'
import { Route as SettingsInterfaceRouteImport } from './routes/settings/interface'
import { Route as SettingsHttpsProxyRouteImport } from './routes/settings/https-proxy'
import { Route as SettingsHardwareRouteImport } from './routes/settings/hardware'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAssistantRouteImport } from './routes/settings/assistant'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as LocalApiServerLogsRouteImport } from './routes/local-api-server/logs'
import { Route as HubModelIdRouteImport } from './routes/hub/$modelId'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocalApiServerRoute = SettingsLocalApiServerRouteImport.update({
  id: '/settings/local-api-server',
  path: '/settings/local-api-server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/settings/interface',
  path: '/settings/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHttpsProxyRoute = SettingsHttpsProxyRouteImport.update({
  id: '/settings/https-proxy',
  path: '/settings/https-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHardwareRoute = SettingsHardwareRouteImport.update({
  id: '/settings/hardware',
  path: '/settings/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/settings/attachments',
  path: '/settings/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/settings/assistant',
  path: '/settings/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalApiServerLogsRoute = LocalApiServerLogsRouteImport.update({
  id: '/local-api-server/logs',
  path: '/local-api-server/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubModelIdRoute = HubModelIdRouteImport.update({
  id: '/hub/$modelId',
  path: '/hub/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub': typeof HubIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/system-monitor'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/hub/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/system-monitor'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/hub'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/system-monitor'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/threads/$threadId'
    | '/hub/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  HubModelIdRoute: typeof HubModelIdRoute
  LocalApiServerLogsRoute: typeof LocalApiServerLogsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHardwareRoute: typeof SettingsHardwareRoute
  SettingsHttpsProxyRoute: typeof SettingsHttpsProxyRoute
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsLocalApiServerRoute: typeof SettingsLocalApiServerRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  HubIndexRoute: typeof HubIndexRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-api-server': {
      id: '/settings/local-api-server'
      path: '/settings/local-api-server'
      fullPath: '/settings/local-api-server'
      preLoaderRoute: typeof SettingsLocalApiServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/interface': {
      id: '/settings/interface'
      path: '/settings/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/https-proxy': {
      id: '/settings/https-proxy'
      path: '/settings/https-proxy'
      fullPath: '/settings/https-proxy'
      preLoaderRoute: typeof SettingsHttpsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hardware': {
      id: '/settings/hardware'
      path: '/settings/hardware'
      fullPath: '/settings/hardware'
      preLoaderRoute: typeof SettingsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/settings/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/settings/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-api-server/logs': {
      id: '/local-api-server/logs'
      path: '/local-api-server/logs'
      fullPath: '/local-api-server/logs'
      preLoaderRoute: typeof LocalApiServerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$modelId': {
      id: '/hub/$modelId'
      path: '/hub/$modelId'
      fullPath: '/hub/$modelId'
      preLoaderRoute: typeof HubModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  HubModelIdRoute: HubModelIdRoute,
  LocalApiServerLogsRoute: LocalApiServerLogsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHardwareRoute: SettingsHardwareRoute,
  SettingsHttpsProxyRoute: SettingsHttpsProxyRoute,
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsLocalApiServerRoute: SettingsLocalApiServerRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  HubIndexRoute: HubIndexRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
