/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsTemporaryRouteImport } from './routes/threads/temporary'
import { Route as ThreadsConversationIdRouteImport } from './routes/threads/$conversationId'
import { Route as ShareSlugRouteImport } from './routes/share/$slug'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsTemporaryRoute = ThreadsTemporaryRouteImport.update({
  id: '/threads/temporary',
  path: '/threads/temporary',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsConversationIdRoute = ThreadsConversationIdRouteImport.update({
  id: '/threads/$conversationId',
  path: '/threads/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/threads/$conversationId': typeof ThreadsConversationIdRoute
  '/threads/temporary': typeof ThreadsTemporaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/threads/$conversationId': typeof ThreadsConversationIdRoute
  '/threads/temporary': typeof ThreadsTemporaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/threads/$conversationId': typeof ThreadsConversationIdRoute
  '/threads/temporary': typeof ThreadsTemporaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/projects/$projectId'
    | '/share/$slug'
    | '/threads/$conversationId'
    | '/threads/temporary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/projects/$projectId'
    | '/share/$slug'
    | '/threads/$conversationId'
    | '/threads/temporary'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/projects/$projectId'
    | '/share/$slug'
    | '/threads/$conversationId'
    | '/threads/temporary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ThreadsConversationIdRoute: typeof ThreadsConversationIdRoute
  ThreadsTemporaryRoute: typeof ThreadsTemporaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/temporary': {
      id: '/threads/temporary'
      path: '/threads/temporary'
      fullPath: '/threads/temporary'
      preLoaderRoute: typeof ThreadsTemporaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$conversationId': {
      id: '/threads/$conversationId'
      path: '/threads/$conversationId'
      fullPath: '/threads/$conversationId'
      preLoaderRoute: typeof ThreadsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ShareSlugRoute: ShareSlugRoute,
  ThreadsConversationIdRoute: ThreadsConversationIdRoute,
  ThreadsTemporaryRoute: ThreadsTemporaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
