#!/usr/bin/env bash

APPIMAGETOOL="./.cache/build-tools/appimagetool"
RELEASE_CHANNEL=${RELEASE_CHANNEL:-"stable"}


# pull in AppImageTool if it's not pre cached
mkdir -p ./.cache/build-tools
if [ ! -f "${APPIMAGETOOL}" ]; then
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O "${APPIMAGETOOL}"
  chmod +x "${APPIMAGETOOL}"
fi


if [[ "${RELEASE_CHANNEL}" != "stable" ]]; then
  APP_DIR=./src-tauri/target/release/bundle/appimage/Jan-${RELEASE_CHANNEL}.AppDir
else
  APP_DIR=./src-tauri/target/release/bundle/appimage/Jan.AppDir
fi

# bundle additional resources in the AppDir without pulling in their dependencies
cp ./src-tauri/resources/bin/bun $APP_DIR/usr/bin/bun
mkdir -p $APP_DIR/usr/lib/Jan/binaries/engines
cp -f ./src-tauri/binaries/deps/*.so* $APP_DIR/usr/lib/Jan/binaries/
cp -f ./src-tauri/binaries/*.so* $APP_DIR/usr/lib/Jan/binaries/
cp -rf ./src-tauri/binaries/engines $APP_DIR/usr/lib/Jan/binaries/

# remove appimage generated by tauri build
APP_IMAGE=./src-tauri/target/release/bundle/appimage/$(ls ./src-tauri/target/release/bundle/appimage/ | grep AppImage | head -1)
echo $APP_IMAGE
rm -f $APP_IMAGE

# repackage appimage with additional resources
"${APPIMAGETOOL}" $APP_DIR $APP_IMAGE
