name: Tauri Builder Flatpak

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build. For example: 0.6.8'
        required: false
      public_provider:
        type: choice
        description: 'Public Provider'
        options:
          - none
          - aws-s3
        default: none

jobs:
  build-linux-x64-flatpak:
    uses: ./.github/workflows/template-tauri-build-linux-x64-flatpak.yml
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    secrets:
      DELTA_AWS_S3_BUCKET_NAME: ${{ secrets.DELTA_AWS_S3_BUCKET_NAME }}
      DELTA_AWS_ACCESS_KEY_ID: ${{ secrets.DELTA_AWS_ACCESS_KEY_ID }}
      DELTA_AWS_SECRET_ACCESS_KEY: ${{ secrets.DELTA_AWS_SECRET_ACCESS_KEY }}
      DELTA_AWS_REGION: ${{ secrets.DELTA_AWS_REGION }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      JAN_SIGNING_KEY: ${{ secrets.JAN_SIGNING_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
      POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
    with:
      ref: ${{ github.ref }}
      public_provider: ${{ inputs.public_provider }}
      new_version: ${{ inputs.version }}
      channel: stable
      disable_updater: true