export const paramsSettings = {
  stream: {
    key: 'stream',
    value: true,
    title: 'Stream',
    description: `Enables real-time response streaming.`,
  },
  max_context_tokens: {
    key: 'max_context_tokens',
    value: 0,
    title: 'Max Context Tokens',
    description: `Total token budget (input + output) for the model. When set (> 0), older messages are automatically trimmed or compacted to stay within this limit. Set to 0 to disable (no trimming). Common values: 4096, 8192, 16384, 32768, 128000.`,
  },
  max_output_tokens: {
    key: 'max_output_tokens',
    value: 2048,
    title: 'Max Output Tokens',
    description: `Maximum number of tokens the model can generate in a single reply. Sent as max_tokens to OpenAI-compatible APIs.`,
  },
  auto_compact: {
    key: 'auto_compact',
    value: false,
    title: 'Auto Compact',
    description: `When enabled and context limit is reached, automatically summarize older messages instead of dropping them. Preserves conversation meaning while reducing token usage. Requires max_context_tokens to be set.`,
  },
  temperature: {
    key: 'temperature',
    value: 0.7,
    title: 'Temperature',
    description: `Controls response randomness. Higher values produce more creative, varied responses. `,
  },
  frequency_penalty: {
    key: 'frequency_penalty',
    value: 0.7,
    title: 'Frequency Penalty',
    description: `Reduces word repetition. Higher values encourage more varied language. Useful for creative writing and content generation.`,
  },
  presence_penalty: {
    key: 'presence_penalty',
    value: 0.7,
    title: 'Presence Penalty',
    description: `Encourages the model to explore new topics. Higher values help prevent the model from fixating on already-discussed subjects.`,
  },
  top_p: {
    key: 'top_p',
    value: 0.95,
    title: 'Top P',
    description: `Set probability threshold for more relevant outputs. Higher values allow more diverse word choices.`,
    controllerType: 'slider',
  },
  top_k: {
    key: 'top_k',
    value: 2,
    title: 'Top K',
    description:
      'Number of most relevant documents to retrieve. Higher values return more results.',
  },
  mirostat: {
    key: 'mirostat',
    value: 0,
    title: 'Mirostat',
    description: `Mirostat sampling mode (llama.cpp only). 0 = disabled, 1 = Mirostat v1, 2 = Mirostat v2.`,
  },
  mirostat_tau: {
    key: 'mirostat_tau',
    value: 5.0,
    title: 'Mirostat Tau',
    description: `Mirostat target entropy (llama.cpp only). Lower values produce more focused output.`,
  },
  mirostat_eta: {
    key: 'mirostat_eta',
    value: 0.1,
    title: 'Mirostat Eta',
    description: `Mirostat learning rate (llama.cpp only).`,
  },
  grammar: {
    key: 'grammar',
    value: '',
    title: 'Grammar (GBNF)',
    description: `GBNF grammar string to constrain generations (llama.cpp only). Paste the grammar contents directly.`,
  },
  json_schema: {
    key: 'json_schema',
    value: '',
    title: 'JSON Schema',
    description: `JSON schema string to constrain generations as valid JSON (llama.cpp only).`,
  },
  typical_p: {
    key: 'typical_p',
    value: 1.0,
    title: 'Typical P',
    description: `Locally-typical sampling (llama.cpp only). 1.0 = disabled. Lower values bias toward tokens whose probability is close to the conditional entropy.`,
  },
  top_n_sigma: {
    key: 'top_n_sigma',
    value: -1.0,
    title: 'Top N Sigma',
    description: `Top-n-sigma sampling (llama.cpp only). -1 = disabled. Filters tokens by standard deviations above the max logit.`,
  },
  dynatemp_range: {
    key: 'dynatemp_range',
    value: 0.0,
    title: 'Dynamic Temperature Range',
    description: `Dynamic temperature range (llama.cpp only). 0 = disabled. The effective temperature is sampled in [temperature - range, temperature + range].`,
  },
  dynatemp_exp: {
    key: 'dynatemp_exp',
    value: 1.0,
    title: 'Dynamic Temperature Exponent',
    description: `Dynamic temperature exponent (llama.cpp only). Shapes the temperature distribution within the dynamic range.`,
  },
  xtc_probability: {
    key: 'xtc_probability',
    value: 0.0,
    title: 'XTC Probability',
    description: `Probability of activating the XTC (Exclude Top Choices) sampler (llama.cpp only). 0 = disabled.`,
  },
  xtc_threshold: {
    key: 'xtc_threshold',
    value: 0.1,
    title: 'XTC Threshold',
    description: `Minimum probability of a token to be considered for XTC exclusion (llama.cpp only). Only used when XTC probability > 0.`,
  },
  dry_multiplier: {
    key: 'dry_multiplier',
    value: 0.0,
    title: 'DRY Multiplier',
    description: `DRY (Don't Repeat Yourself) penalty multiplier (llama.cpp only). 0 = disabled. Penalizes sequences that have appeared before in the context.`,
  },
  dry_base: {
    key: 'dry_base',
    value: 1.75,
    title: 'DRY Base',
    description: `DRY penalty base (llama.cpp only). Exponential base for penalty growth as repeated-sequence length increases.`,
  },
  dry_allowed_length: {
    key: 'dry_allowed_length',
    value: 2,
    title: 'DRY Allowed Length',
    description: `Minimum repeated-sequence length before DRY starts penalizing (llama.cpp only).`,
  },
  dry_penalty_last_n: {
    key: 'dry_penalty_last_n',
    value: -1,
    title: 'DRY Penalty Window',
    description: `Window of recent tokens DRY scans for repetitions (llama.cpp only). 0 = disabled, -1 = full context.`,
  },
  ignore_eos: {
    key: 'ignore_eos',
    value: false,
    title: 'Ignore EOS',
    description: `Continue generating past the end-of-sequence token (llama.cpp only). Useful for forcing the model to fill a token budget.`,
  },
}

export const LLAMACPP_ONLY_PARAM_KEYS: ReadonlySet<string> = new Set([
  'mirostat',
  'mirostat_tau',
  'mirostat_eta',
  'grammar',
  'json_schema',
  'typical_p',
  'top_n_sigma',
  'dynatemp_range',
  'dynatemp_exp',
  'xtc_probability',
  'xtc_threshold',
  'dry_multiplier',
  'dry_base',
  'dry_allowed_length',
  'dry_penalty_last_n',
  'ignore_eos',
])
