/* eslint-disable @typescript-eslint/no-explicit-any */
export const presetConfiguration: Record<string, any> = {
  prompt_template: {
    key: 'prompt_template',
    title: 'Prompt template',
    description: `A structured format that guides how the model should respond.`,
    controller_type: 'textarea',
    controller_props: {
      placeholder: 'Prompt template',
      value: '',
      rows: 4,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  stop: {
    key: 'stop',
    title: 'Stop',
    description: `Defines tokens or phrases that will end the model's response.`,
    controller_type: 'tag',
    controller_props: {
      placeholder: 'Enter stop words',
      value: [''],
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  ctx_len: {
    key: 'ctx_len',
    title: 'Context Length',
    description: `Controls how much text the model can consider at once. Longer context allows the model to handle more input but uses more memory and runs slower.`,
    controller_type: 'slider',
    controller_props: {
      min: 128,
      max: 4096,
      step: 128,
      value: 4096,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  max_tokens: {
    key: 'max_tokens',
    title: 'Max Tokens',
    description: `Controls response length. Higher values allow longer, more detailed responses.`,
    controller_type: 'slider',
    controller_props: {
      min: 100,
      max: 4096,
      step: 10,
      value: 4096,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  ngl: {
    key: 'ngl',
    title: 'Number of GPU layers (ngl)',
    description:
      'Controls how many layers of the model run on GPU. More layers means faster processing, but requires more GPU memory.',
    controller_type: 'slider',
    controller_props: {
      min: 1,
      max: 100,
      step: 1,
      value: 100,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  embedding: {
    key: 'embedding',
    title: 'Embedding',
    description: 'Whether to enable embedding.',
    controller_type: 'checkbox',
    controller_props: {
      value: true,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  stream: {
    key: 'stream',
    title: 'Stream',
    description: `Enables real-time response streaming.`,
    controller_type: 'checkbox',
    controller_props: {
      value: false,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  temperature: {
    key: 'temperature',
    title: 'Temperature',
    description: `Controls response randomness. Higher values produce more creative, varied responses. `,
    controller_type: 'slider',
    controller_props: {
      min: 0,
      max: 2,
      step: 0.1,
      value: 0.7,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  frequency_penalty: {
    key: 'frequency_penalty',
    title: 'Frequency Penalty',
    description: `Reduces word repetition. Higher values encourage more varied language. Useful for creative writing and content generation.`,
    controller_type: 'slider',
    controller_props: {
      min: 0,
      max: 1,
      step: 0.1,
      value: 0.7,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  presence_penalty: {
    key: 'presence_penalty',
    title: 'Presence Penalty',
    description: `Encourages the model to explore new topics. Higher values help prevent the model from fixating on already-discussed subjects.`,
    controller_type: 'slider',
    controller_props: {
      min: 0,
      max: 1,
      step: 0.1,
      value: 0.7,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  top_p: {
    key: 'top_p',
    title: 'Top P',
    description: `Set probability threshold for more relevant outputs. Higher values allow more diverse word choices.`,
    controller_type: 'slider',
    controller_props: {
      min: 0,
      max: 1,
      step: 0.1,
      value: 0.95,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  cpu_threads: {
    key: 'cpu_threads',
    title: 'CPU Threads',
    description:
      'Controls how many CPU cores are used for processing. Higher values can speed up model loading but use more system resources.',
    controller_type: 'slider',
    controller_props: {
      min: 0,
      max: 128,
      step: 1,
      value: 1,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  // assistant
  chunk_size: {
    key: 'chunk_size',
    title: 'Chunk Size',
    description:
      'Sets the maximum number of tokens per data chunk. Increase size for processing large blocks of text efficiently, or decrease it to optimize memory usage.',
    controller_type: 'slider',
    controller_props: {
      min: 128,
      max: 2048,
      step: 128,
      value: 1024,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  chunk_overlap: {
    key: 'chunk_overlap',
    title: 'Chunk Overlap',
    description:
      'How many words overlap between text segments. More overlap helps maintain meaning across splits.',
    controller_type: 'slider',
    controller_props: {
      min: 32,
      max: 512,
      step: 32,
      value: 64,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
  top_k: {
    key: 'top_k',
    title: 'Top K',
    description:
      'Number of most relevant documents to retrieve. Higher values return more results.',
    controller_type: 'slider',
    controller_props: {
      min: 1,
      max: 5,
      step: 1,
      value: 2,
    },
    require_model_reload: false,
    config_type: 'runtime',
  },
  retrieval_template: {
    key: 'retrieval_template',
    title: 'Retrieval Template',
    description: 'Format for how the AI uses context to answer questions.',
    controller_type: 'textarea',
    controller_props: {
      placeholder: 'Retrieval Template',
      value: '',
      rows: 4,
    },
    require_model_reload: true,
    config_type: 'setting',
  },
}
